# Generated by Django 5.2.5 on 2025-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('pesona', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Elektronik'), ('FASHION', 'Fashion'), ('HOME', 'Peralatan Rumah'), ('FOOD', 'Makanan & Minuman'), ('SPORTS', 'Olahraga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
