# Generated by Django 5.2.5 on 2025-09-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_remove_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Toko',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
