# Generated by Django 5.2.5 on 2025-09-14 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_product_toko_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
