# Generated by Django 5.2.5 on 2025-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_toko_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toko',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
